import type { Config } from "tailwindcss";

// Token system mirrors the reference asset (index.html) and DESIGN.md.
// The concrete HTML asset is the authoritative visual source of truth.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#ffdeac",
        "surface-well": "#000000",
        "on-primary-fixed": "#00210c",
        "inverse-on-surface": "#2d3136",
        "outline-variant": "#3d4a3e",
        outline: "#869486",
        primary: "#ffffff",
        "border-active": "#203653",
        "border-subtle": "#0f1622",
        error: "#ffb4ab",
        "on-tertiary": "#432c00",
        "on-secondary-container": "#002e3b",
        "on-surface": "#e0e2e9",
        "on-surface-variant": "#bacbb9",
        "on-primary-fixed-variant": "#005226",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#006d35",
        "secondary-fixed": "#b7eaff",
        "status-red": "#ef4444",
        "surface-variant": "#31353a",
        "primary-fixed": "#73fd9c",
        "surface-panel": "#101418",
        "primary-fixed-dim": "#54e083",
        "on-tertiary-fixed": "#281900",
        "surface-container-high": "#272a2f",
        "secondary-container": "#159dc0",
        "on-primary": "#003918",
        "on-secondary-fixed": "#001f28",
        "secondary-fixed-dim": "#65d4f9",
        "error-container": "#93000a",
        "surface-container-lowest": "#0b0f13",
        "primary-container": "#73fd9c",
        "inverse-surface": "#e0e2e9",
        tertiary: "#ffffff",
        "on-tertiary-container": "#865c00",
        "surface-container-low": "#181c20",
        "on-secondary-fixed-variant": "#004e61",
        surface: "#101418",
        "on-secondary": "#003543",
        "surface-bright": "#36393e",
        "on-primary-container": "#007438",
        "tertiary-fixed": "#ffdeac",
        "surface-container": "#1c2024",
        "on-tertiary-fixed-variant": "#604100",
        background: "#101418",
        "on-error": "#690005",
        "label-muted": "#5d6b87",
        "surface-container-highest": "#31353a",
        "surface-tint": "#54e083",
        "on-background": "#e0e2e9",
        "surface-dim": "#101418",
        "tertiary-fixed-dim": "#ffba38",
        secondary: "#65d4f9",
      },
      spacing: {
        "header-h": "48px",
        "sidebar-w": "256px",
        "footer-h": "32px",
        gutter: "1px",
        "panel-pad": "0.75rem",
      },
      fontFamily: {
        mono: ["JetBrains Mono", "Cascadia Mono", "Consolas", "monospace"],
      },
      fontSize: {
        "label-micro": ["8px", { letterSpacing: "0.05em", fontWeight: "700" }],
        "label-caps": ["10px", { letterSpacing: "0.12em", fontWeight: "800" }],
        telemetry: ["10px", { letterSpacing: "0.1em", fontWeight: "900" }],
        "body-md": ["12px", { lineHeight: "1.5", fontWeight: "500" }],
        "headline-md": ["14px", { letterSpacing: "0.2em", fontWeight: "900" }],
        "display-frequency": ["22px", { letterSpacing: "0.1em", fontWeight: "900" }],
        "headline-lg": ["26px", { lineHeight: "1.2", fontWeight: "900" }],
      },
      boxShadow: {
        // Tactical glows: 0px blur, themed spread (DESIGN.md "Glow" utilities)
        "cyan-glow": "0 0 15px rgba(101, 212, 249, 0.3)",
        "emerald-led": "0 0 8px rgba(115,253,156,0.6)",
        "amber-glow": "0 0 8px rgba(255,186,56,0.6)",
        well: "inset 0 2px 4px rgba(0,0,0,0.8)",
      },
    },
  },
  plugins: [],
} satisfies Config;
